name: CI/CD
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  REMOTE_DIRECTORY: <remote-directory>

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: dotnet publish ShowCase-MVC/ShowCase-MVC.csproj -c Release -o publish/

      - name: Copy files to server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: publish/
          target: ${{ env.REMOTE_DIRECTORY }}
